### ISSUE TITLE
Suggestion: supporting PR comments instead of GH issues

### ISSUE THREAD

**Issue by Gby56** [lerer-veracode/Veracode-manual-for-GitHub#1]
Hi !
We're currently users of Veracode, mostly with jenkins, and scanning PRs is really the best of both worlds in my opinion.

I know other scanners are able to only review the diff, not with a deep SAST analysis of course, but they do gain a simple advantage... they prevent introducing the issues in the production branches efficiently.

Now I know that pipeline scan is intended for that, and it may be fairly fast, but the main and only gripe I have is that most of the support is on Github issues, which don't really translate to issues that "don't really exist yet", since they are not merged yet.

In my opinion the comments in PRs should be used, and I maintain https://github.com/security-alert/security-alert for that purpose (using SARIF input, to comment issues in PRs)

If the veracode wrapper could do that out of the box it would be great for compatibility (and not just GH actions)

**Comment by Gby56** [comment]
PS: same goes for Github code scanning alerts, this is a paid feature that most veracode customers won't pay for, since it's expensive and include CodeQL, which would then make Veracode redundant. So PR comments is the most versatile and lower noise compared to issues or code scanning alerts

**Comment by Gby56** [comment]
@julz0815 do you want me to clone that issue to one of the forks ? the official one on the veracode org ?

**Comment by Lerer** [comment]
Yes, please!
This repo will not get further updates.

Once cloned, you can close this.

**Comment by Gby56** [comment]
Perfect ! And I just realized you had https://github.com/Lerer/veracode-pipeline-PR-comment actually ! which fits my description perfectly, I think this should be merged into the main veracode actions etc...

**Comment by Gby56** [comment]
Actually, that's only going to be cloned if @julz0815 enables issues on https://github.com/julz0815/Veracode-manual-for-GitHub or https://github.com/veracode/Veracode-manual-for-GitHub

**Comment by julz0815** [comment]
Hi Gabriel,

I have enabled issues and discussions at https://github.com/veracode/Veracode-manual-for-GitHub, this will be the official repo with the manual. It needs to be updated as there are already some more official actions available.

Best regards / Mit freundlichen Grüßen


[A picture containing gear  Description automatically generated]

Julian Totzek-Hallhuber   //  Manager Solution Architects EMEA & APAC
OFFICE: +49.6128.9371777  //   MOBILE: +49.160.97285004

LinkedIn:       http://de.linkedin.com/pub/julian-totzek-hallhuber/0/738/b65/
XING:              https://www.xing.com/profile/Julian_TotzekHallhuber
Twitter:    @d3v_rand0m


From: Gabriel Marquet ***@***.***>
Date: Tuesday, 21. June 2022 at 11:13
To: lerer-veracode/Veracode-manual-for-GitHub ***@***.***>
Cc: Julian Totzek-Hallhuber ***@***.***>, Mention ***@***.***>
Subject: Re: [lerer-veracode/Veracode-manual-for-GitHub] Suggestion: supporting PR comments instead of GH issues (Issue #1)

Actually, that's only going to be cloned if @julz0815<https://github.com/julz0815> enables issues on https://github.com/julz0815/Veracode-manual-for-GitHub or https://github.com/veracode/Veracode-manual-for-GitHub
